# Laboratorio 8 DW: Feature Engineering

## Import Data

In [4]:
import numpy as np
import pandas as pd

In [9]:
titanic = pd.read_csv('titanic_MD.csv')
titanicfull = pd.read_csv('titanic.csv')

In [7]:
titanic.head()

PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...       ?  38.0    1.0   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
2                            McCarthy, Mr. Timothy J    male  54.0    0.0   
3                    Sandstrom, Miss. Marguerite Rut  female   NaN    1.0   
4                           Bonnell, Miss. Elizabeth  female  58.0    NaN   

   Parch    Ticket     Fare Cabin Embarked  
0    0.0  PC 17599  71.2833   C85        C  
1    0.0    113803  53.1000  C123        S  
2    0.0     17463  51.8625   E46        S  
3    NaN   PP 9549  16.7000    G6        S  
4    0.0    113783  26.5500  C103        S

In [8]:
titanicfull.head()

PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                            McCarthy, Mr. Timothy J    male  54.0      0   
3                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
4                           Bonnell, Miss. Elizabeth  female  58.0      0   

   Parch    Ticket     Fare Cabin Embarked  
0      0  PC 17599  71.2833   C85        C  
1      0    113803  53.1000  C123        S  
2      0     17463  51.8625   E46        S  
3      1   PP 9549  16.7000    G6        S  
4      0    113783  26.5500  C103        S

## Parte 1

### Missing Data: Reporte detallado

In [9]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  158.000000  180.000000   
mean    455.366120    0.672131    1.191257   35.692532    0.461111   
std     247.052476    0.470725    0.515187   15.640858    0.646122   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   35.500000    0.000000   
75%     676.000000    1.000000    1.000000   48.000000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  171.000000  175.000000  
mean     0.461988   78.959191  
std      0.753435   77.026328  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   56.929200  
75%      1.000000   90.539600  
max      4.000000  512.329200

In [10]:
titanic.isna().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            25
SibSp           3
Parch          12
Ticket          0
Fare            8
Cabin           0
Embarked       12
dtype: int64

Como podemos notar en las columnas "Age, Parch, SibSp, Fare, Embarked" contienen valores como NAs, estos valores deben ser reemplazados, tambien notamos que la columna "Sex" posee datos extraños pero no son Nas, a continuación análizaremos los datos que contiene la variable.

In [14]:
np.unique(titanic['Sex'])

array(['?', 'female', 'male'], dtype=object)

Al analizar la columna "Sex" vemos que posee missing data en forma de "?", analizaremos las demas columnas para ver si contienen algun otro dato erroneo.

In [15]:
np.unique(titanic['Survived'])

array([0, 1], dtype=int64)

In [16]:
np.unique(titanic['Pclass'])

array([1, 2, 3], dtype=int64)

In [17]:
np.unique(titanic['Ticket'])

array(['110152', '110413', '110465', '110564', '110813', '111240',
       '111320', '111361', '111369', '112050', '112053', '112059',
       '112277', '113043', '113050', '113051', '113055', '113501',
       '113503', '113505', '113509', '113514', '113760', '113773',
       '113776', '113781', '113783', '113784', '113786', '113787',
       '113788', '113803', '113806', '11751', '11752', '11753', '11755',
       '11765', '11767', '11769', '11771', '11813', '11967', '12749',
       '13049', '13213', '13214', '13502', '13507', '13509', '13567',
       '13568', '16966', '17421', '17453', '17463', '17465', '17466',
       '17474', '17764', '19877', '19928', '19943', '19950', '19952',
       '19996', '230080', '230136', '24160', '248698', '248733', '27042',
       '27267', '28551', '33638', '34218', '347054', '348121', '348123',
       '348124', '35273', '35281', '36928', '36947', '36963', '36967',
       '36973', '392096', '5727', '695', 'C.A. 29395', 'C.A. 34260',
       'F.C. 12750', 'PC 

In [18]:
np.unique(titanic['Cabin'])

array(['A10', 'A16', 'A20', 'A23', 'A24', 'A26', 'A31', 'A34', 'A36',
       'A5', 'A6', 'A7', 'B101', 'B18', 'B19', 'B20', 'B22', 'B3', 'B30',
       'B35', 'B37', 'B38', 'B39', 'B4', 'B41', 'B42', 'B49', 'B5', 'B50',
       'B51 B53 B55', 'B57 B59 B63 B66', 'B58 B60', 'B69', 'B71', 'B73',
       'B77', 'B79', 'B80', 'B82 B84', 'B86', 'B94', 'B96 B98', 'C101',
       'C103', 'C104', 'C110', 'C111', 'C118', 'C123', 'C124', 'C125',
       'C126', 'C148', 'C2', 'C22 C26', 'C23 C25 C27', 'C30', 'C32',
       'C45', 'C46', 'C49', 'C50', 'C52', 'C54', 'C62 C64', 'C65', 'C68',
       'C7', 'C70', 'C78', 'C82', 'C83', 'C85', 'C86', 'C87', 'C90',
       'C91', 'C92', 'C93', 'C99', 'D', 'D10 D12', 'D11', 'D15', 'D17',
       'D19', 'D20', 'D26', 'D28', 'D30', 'D33', 'D35', 'D36', 'D37',
       'D46', 'D47', 'D48', 'D49', 'D50', 'D56', 'D6', 'D7', 'D9', 'E10',
       'E101', 'E12', 'E121', 'E17', 'E24', 'E25', 'E31', 'E33', 'E34',
       'E36', 'E38', 'E40', 'E44', 'E46', 'E49', 'E50', 'E58', 'E

Unicamente la columna "Sex" posee datos distintos a "NAs", ahora contaremos cuantos datos faltantes existen.

In [20]:
cols = []
val = []
for col in titanic.select_dtypes(include='object').columns:
    cols.append(col)
    val.append(titanic[col].str.contains(r'\?').sum())
pd.DataFrame({
    'cols':cols,
    'val':val
})

cols  val
0      Name    0
1       Sex   51
2    Ticket    0
3     Cabin    0
4  Embarked    0

### Detalle de los datos

* **Age:** 25 missing values de tipo (NAs)
* **SibSp:** 3 missing values de tipo (NAs)
* **Parch:** 12 missing values de tipo (NAs)
* **Fare:** 8 missing values de tipo (NAs)
* **Embarked:** 12 missing values de tipo (NAs)
* **Sex:** 51 missing values de tipo (?)

### Especificar el tipo de modelo de modelo que se utilizará y que valores se le daran a los missing values de cada columna

* **Age:** Para la variable de edad se utilizara un imputación de la mediana para los valores faltantes, ya que la distribución de los datos es normal y reemplazar los datos con la mediana ayudará a mantener los datos en el limite central.

* **SibSp:** Para la variable de acompañantes abordo se utilizará una imputación de moda para los valores faltantes, ya que al ser una variable categoritca y son tan poco missin values en comparación con el total, lo mejor es reemplazar esos valores con la moda de la distrbución.

* **Parch:** Para la variable de familiares abordo se utilizará de igual fomra una imputaciónd ela moda por ser también una variable categorica.

* **Fare:** Para la variable de Fare se relaizará una imputación de la mediana, ya que los datos están muy sesgados y esta ayudara a normalizar la distribución.

* **Embarked:** Para la variable embarked se utilizará una imputación de la moda para sus valores faltantes, ya que son muy pocos.

* **Sex:** Para la variable de sexo se utilizará una logistic regression, ya que los datos con valores "?" representan hasta el 30% de los datos.

### Reporte de datos completos

Las columnas de ID y los nombres se encuentran en el grupo de los datos completos, pero no se tomará en cuenta porque no es relevante para un análisis.

* **Survived:** Posee datos de tipo binario (0 y 1)
* **Ticket:** Posee los datos de los números de ticket
* **Cabin:** Posee los números de cabina de los pasajeros
* **Pclass:** Posee las clases de vieje para los pasajeros

### Utilizar los siguientes métodos para cada columna que contiene missing values

* Imputación general (moda, mediana y media)
* Modelo de regresión lineal
* Outliers (SDA o PA)


#### Imputación por moda

In [7]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [30]:
titanic['new_sibsp'] = imp_mode.fit_transform(titanic[['SibSp']])
imp_mode.fit_transform(titanic[['SibSp']])

array([[1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [3.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [3.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [3.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [29]:
titanic['new_parch'] = imp_mode.fit_transform(titanic[['Parch']])
imp_mode.fit_transform(titanic[['Parch']])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],

In [28]:
titanic['new_embarked'] = imp_mode.fit_transform(titanic[['Embarked']])
imp_mode.fit_transform(titanic[['Embarked']])

array([['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

#### Imputación por mediana

In [14]:
imp_median.fit_transform(titanic[['Age']])

array([[38.  ],
       [35.  ],
       [54.  ],
       [35.5 ],
       [58.  ],
       [34.  ],
       [35.5 ],
       [19.  ],
       [49.  ],
       [65.  ],
       [45.  ],
       [29.  ],
       [25.  ],
       [35.5 ],
       [46.  ],
       [71.  ],
       [23.  ],
       [21.  ],
       [47.  ],
       [24.  ],
       [35.5 ],
       [54.  ],
       [19.  ],
       [37.  ],
       [24.  ],
       [36.5 ],
       [22.  ],
       [61.  ],
       [56.  ],
       [50.  ],
       [35.5 ],
       [ 3.  ],
       [44.  ],
       [58.  ],
       [ 2.  ],
       [40.  ],
       [31.  ],
       [32.  ],
       [38.  ],
       [35.5 ],
       [44.  ],
       [37.  ],
       [35.5 ],
       [62.  ],
       [30.  ],
       [52.  ],
       [40.  ],
       [35.5 ],
       [35.  ],
       [37.  ],
       [63.  ],
       [19.  ],
       [36.  ],
       [ 2.  ],
       [50.  ],
       [ 0.92],
       [17.  ],
       [30.  ],
       [24.  ],
       [18.  ],
       [31.  ],
       [40.  ],
       [

In [19]:
titanic['new_age'] = imp_median.fit_transform(titanic[['Age']])

In [27]:
titanic['new_fare'] = imp_median.fit_transform(titanic[['Fare']])
imp_median.fit_transform(titanic[['Fare']])

array([[ 71.2833],
       [ 53.1   ],
       [ 51.8625],
       [ 16.7   ],
       [ 26.55  ],
       [ 13.    ],
       [ 35.5   ],
       [263.    ],
       [ 76.7292],
       [ 61.9792],
       [ 83.475 ],
       [ 10.5   ],
       [ 56.9292],
       [263.    ],
       [ 61.175 ],
       [ 34.6542],
       [ 63.3583],
       [ 77.2875],
       [ 52.    ],
       [247.5208],
       [ 13.    ],
       [ 77.2875],
       [ 26.2833],
       [ 53.1   ],
       [ 79.2   ],
       [ 26.    ],
       [ 66.6   ],
       [ 33.5   ],
       [ 30.6958],
       [ 28.7125],
       [ 39.    ],
       [ 26.    ],
       [ 27.7208],
       [146.5208],
       [ 10.4625],
       [ 31.    ],
       [113.275 ],
       [ 56.9292],
       [ 90.    ],
       [ 83.475 ],
       [ 90.    ],
       [ 52.5542],
       [ 10.4625],
       [ 26.55  ],
       [ 56.9292],
       [ 79.65  ],
       [  0.    ],
       [153.4625],
       [135.6333],
       [ 29.7   ],
       [ 77.9583],
       [ 91.0792],
       [ 12.

#### Imputación por regresión lineal

In [16]:
from sklearn.linear_model import LinearRegression

In [24]:
lm = LinearRegression()
lm = lm.fit(titanicfull[['Sex']],titanicfull[['Age']])
lm

ValueError: could not convert string to float: 'female'

### Comparar los métodos utilizados en el inciso anterior

Como podemos notar las variables por imputación general se acercan mucho a la realidad del dataset completo y las imputaciones por mediana y moda ayudaron a normalizar las distribuciones que sufrian de sesgos.

### Conclusiones PARTE 1

El trabajar con missing data es una parte muy importante para el analisis de datos, siemrpre hay que verificar que las columnas o variables sean del tipo que deben ser (categoricas, númericas, etc) luego hay que entender el efecto que tienen esos valores faltantes en la data para saber que tipo de imputación utilizar para corregir de la mejor forma los errores.

## Parte 2

### Normlice las columnas numéricas por los métodos:

* Standarization
* MinMaxScaling
* MaxAbsScaler

#### Standarization

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()
titanic_z = titanic.copy()
for col in titanic_z.select_dtypes(include=['float', 'int']).columns:
    titanic_z[col+'_z'] = scaler.fit_transform(titanic_z[[col]])

In [33]:
titanic_z.head()

PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...       ?  38.0    1.0   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
2                            McCarthy, Mr. Timothy J    male  54.0    0.0   
3                    Sandstrom, Miss. Marguerite Rut  female   NaN    1.0   
4                           Bonnell, Miss. Elizabeth  female  58.0    NaN   

   Parch    Ticket     Fare  ... Survived_z  Pclass_z     Age_z   SibSp_z  \
0    0.0  PC 17599  71.2833  ...   0.698430 -0.372256  0.147997  0.836362   
1    0.0    113803  53.1000  ...   0.698430 -0.372256 -0.044418  0.836362   
2    0.0     17463  51.8625  ...  -1.431782 -0.372256  1.174212 -0.715650   
3    NaN   PP 9549  16.7000  ...   0.698430  3.520480       NaN  0.836362   
4    0.0    113783  26.5500  ...   0.698430 -0.372256  1.430765       NaN   

    Parch_z    Fare_z  new_age_z  new_fare_z  new_parch_z  new_sibsp_z  
0 -0.614977 -0.099939   0.161090   -0.089215    -0.587235     0.851565  
1 -0.614977 -0.336682  -0.045987   -0.330875    -0.587235     0.851565  
2 -0.614977 -0.352794   1.265501   -0.347322    -0.587235    -0.706799  
3       NaN -0.810604  -0.011474   -0.814639    -0.587235     0.851565  
4 -0.614977 -0.682359   1.541603   -0.683730    -0.587235    -0.706799  

[5 rows x 28 columns]

In [34]:
titanic_z.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  158.000000  180.000000   
mean    455.366120    0.672131    1.191257   35.692532    0.461111   
std     247.052476    0.470725    0.515187   15.640858    0.646122   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   35.500000    0.000000   
75%     676.000000    1.000000    1.000000   48.000000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare    new_age    new_fare   new_parch  ...  \
count  171.000000  175.000000  183.00000  183.000000  183.000000  ...   
mean     0.461988   78.959191   35.66623   77.996131    0.431694  ...   
std      0.753435   77.026328   14.52711   75.449730    0.737147  ...   
min      0.000000    0.000000    0.92000    0.000000    0.000000  ...   
25%      0.000000   29.700000   25.00000   30.000000    0.000000  ...   
50%      0.000000   56.929200   35.50000   56.929200    0.000000  ...   
75%      1.000000   90.539600   46.50000   90.000000    1.000000  ...   
max      4.000000  512.329200   80.00000  512.329200    4.000000  ...   

         Survived_z      Pclass_z         Age_z       SibSp_z       Parch_z  \
count  1.830000e+02  1.830000e+02  1.580000e+02  1.800000e+02  1.710000e+02   
mean   2.062709e-17  4.307423e-17 -2.009644e-16  1.850372e-17  3.116416e-17   
std    1.002743e+00  1.002743e+00  1.003180e+00  1.002789e+00  1.002937e+00   
min   -1.431782e+00 -3.722562e-01 -2.230255e+00 -7.156502e-01 -6.149769e-01   
25%   -1.431782e+00 -3.722562e-01 -7.499403e-01 -7.156502e-01 -6.149769e-01   
50%    6.984303e-01 -3.722562e-01 -1.234867e-02 -7.156502e-01 -6.149769e-01   
75%    6.984303e-01 -3.722562e-01  7.893814e-01  8.363623e-01  7.161756e-01   
max    6.984303e-01  3.520480e+00  2.841810e+00  3.940387e+00  4.709633e+00   

           Fare_z     new_age_z    new_fare_z   new_parch_z   new_sibsp_z  
count  175.000000  1.830000e+02  1.830000e+02  1.830000e+02  1.830000e+02  
mean     0.000000 -8.408195e-18  7.401487e-17  1.092023e-17  3.033396e-17  
std      1.002869  1.002743e+00  1.002743e+00  1.002743e+00  1.002743e+00  
min     -1.028035 -2.398382e+00 -1.036586e+00 -5.872348e-01 -7.067991e-01  
25%     -0.641346 -7.362436e-01 -6.378791e-01 -5.872348e-01 -7.067991e-01  
50%     -0.286827 -1.147410e-02 -2.799841e-01 -5.872348e-01 -7.067991e-01  
75%      0.150775  7.478083e-01  1.595341e-01  7.730686e-01  8.515651e-01  
max      5.642402  3.060168e+00  5.772382e+00  4.853979e+00  3.968293e+00  

[8 rows x 22 columns]

#### MinMaxScaler

In [35]:
from sklearn.preprocessing import MinMaxScaler

In [36]:
scaler = MinMaxScaler()
titanic_norm = titanic.copy()
for col in titanic_norm.select_dtypes(include=['float', 'int']).columns:
    titanic_norm[col+'_norm'] = scaler.fit_transform(titanic_norm[[col]])

In [37]:
titanic_norm.head()

PassengerId  Survived  Pclass  \
0            2         1       1   
1            4         1       1   
2            7         0       1   
3           11         1       3   
4           12         1       1   

                                                Name     Sex   Age  SibSp  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...       ?  38.0    1.0   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
2                            McCarthy, Mr. Timothy J    male  54.0    0.0   
3                    Sandstrom, Miss. Marguerite Rut  female   NaN    1.0   
4                           Bonnell, Miss. Elizabeth  female  58.0    NaN   

   Parch    Ticket     Fare  ... Survived_norm Pclass_norm  Age_norm  \
0    0.0  PC 17599  71.2833  ...           1.0         0.0  0.468892   
1    0.0    113803  53.1000  ...           1.0         0.0  0.430956   
2    0.0     17463  51.8625  ...           0.0         0.0  0.671219   
3    NaN   PP 9549  16.7000  ...           1.0         1.0       NaN   
4    0.0    113783  26.5500  ...           1.0         0.0  0.721801   

   SibSp_norm Parch_norm  Fare_norm  new_age_norm  new_fare_norm  \
0    0.333333        0.0   0.139136      0.468892       0.139136   
1    0.333333        0.0   0.103644      0.430956       0.103644   
2    0.000000        0.0   0.101229      0.671219       0.101229   
3    0.333333        NaN   0.032596      0.437279       0.032596   
4         NaN        0.0   0.051822      0.721801       0.051822   

   new_parch_norm  new_sibsp_norm  
0             0.0        0.333333  
1             0.0        0.333333  
2             0.0        0.000000  
3             0.0        0.333333  
4             0.0        0.000000  

[5 rows x 28 columns]

In [38]:
titanic_norm.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  158.000000  180.000000   
mean    455.366120    0.672131    1.191257   35.692532    0.461111   
std     247.052476    0.470725    0.515187   15.640858    0.646122   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   35.500000    0.000000   
75%     676.000000    1.000000    1.000000   48.000000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare    new_age    new_fare   new_parch  ...  \
count  171.000000  175.000000  183.00000  183.000000  183.000000  ...   
mean     0.461988   78.959191   35.66623   77.996131    0.431694  ...   
std      0.753435   77.026328   14.52711   75.449730    0.737147  ...   
min      0.000000    0.000000    0.92000    0.000000    0.000000  ...   
25%      0.000000   29.700000   25.00000   30.000000    0.000000  ...   
50%      0.000000   56.929200   35.50000   56.929200    0.000000  ...   
75%      1.000000   90.539600   46.50000   90.000000    1.000000  ...   
max      4.000000  512.329200   80.00000  512.329200    4.000000  ...   

       Survived_norm  Pclass_norm    Age_norm  SibSp_norm  Parch_norm  \
count     183.000000   183.000000  158.000000  180.000000  171.000000   
mean        0.672131     0.095628    0.439713    0.153704    0.115497   
std         0.470725     0.257593    0.197785    0.215374    0.188359   
min         0.000000     0.000000    0.000000    0.000000    0.000000   
25%         0.000000     0.000000    0.291856    0.000000    0.000000   
50%         1.000000     0.000000    0.437279    0.000000    0.000000   
75%         1.000000     0.000000    0.595346    0.333333    0.250000   
max         1.000000     1.000000    1.000000    1.000000    1.000000   

        Fare_norm  new_age_norm  new_fare_norm  new_parch_norm  new_sibsp_norm  
count  175.000000    183.000000     183.000000      183.000000      183.000000  
mean     0.154118      0.439381       0.152238        0.107923        0.151184  
std      0.150345      0.183701       0.147268        0.184287        0.214486  
min      0.000000      0.000000       0.000000        0.000000        0.000000  
25%      0.057971      0.304502       0.058556        0.000000        0.000000  
50%      0.111118      0.437279       0.111118        0.000000        0.000000  
75%      0.176722      0.576378       0.175668        0.250000        0.333333  
max      1.000000      1.000000       1.000000        1.000000        1.000000  

[8 rows x 22 columns]

#### MaxAbsScaler

Como podemos notar en el resumen estadistico de cada modelo de escala, la escala mejor optimizada para los datos es la de Min Max Scaling.